// Code generated by protoc-gen-go. DO NOT EDIT.
// source: restrpc/rest.proto

package restrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RestEmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestEmptyResponse) Reset()         { *m = RestEmptyResponse{} }
func (m *RestEmptyResponse) String() string { return proto.CompactTextString(m) }
func (*RestEmptyResponse) ProtoMessage()    {}
func (*RestEmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be8cc7321fde08b2, []int{0}
}

func (m *RestEmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestEmptyResponse.Unmarshal(m, b)
}
func (m *RestEmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestEmptyResponse.Marshal(b, m, deterministic)
}
func (m *RestEmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestEmptyResponse.Merge(m, src)
}
func (m *RestEmptyResponse) XXX_Size() int {
	return xxx_messageInfo_RestEmptyResponse.Size(m)
}
func (m *RestEmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestEmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestEmptyResponse proto.InternalMessageInfo

//  WebSocket request and response JSon messages
type WebSocketError struct {
	HttpCode             uint32   `protobuf:"varint,1,opt,name=http_code,json=httpCode,proto3" json:"http_code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebSocketError) Reset()         { *m = WebSocketError{} }
func (m *WebSocketError) String() string { return proto.CompactTextString(m) }
func (*WebSocketError) ProtoMessage()    {}
func (*WebSocketError) Descriptor() ([]byte, []int) {
	return fileDescriptor_be8cc7321fde08b2, []int{1}
}

func (m *WebSocketError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebSocketError.Unmarshal(m, b)
}
func (m *WebSocketError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebSocketError.Marshal(b, m, deterministic)
}
func (m *WebSocketError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebSocketError.Merge(m, src)
}
func (m *WebSocketError) XXX_Size() int {
	return xxx_messageInfo_WebSocketError.Size(m)
}
func (m *WebSocketError) XXX_DiscardUnknown() {
	xxx_messageInfo_WebSocketError.DiscardUnknown(m)
}

var xxx_messageInfo_WebSocketError proto.InternalMessageInfo

func (m *WebSocketError) GetHttpCode() uint32 {
	if m != nil {
		return m.HttpCode
	}
	return 0
}

func (m *WebSocketError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//  WebSocket request and response protobuf messages
type WebSocketProtobufRequest struct {
	// The rest endpoint to send the request to
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// An arbitrary string which will be reflected back in the response
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	HasMore   bool   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// The data to post to the REST endpoint, if any.
	// Make sure this is the correct data structure based on the endpoint you are posting to.
	Payload              *anypb.Any `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *WebSocketProtobufRequest) Reset()         { *m = WebSocketProtobufRequest{} }
func (m *WebSocketProtobufRequest) String() string { return proto.CompactTextString(m) }
func (*WebSocketProtobufRequest) ProtoMessage()    {}
func (*WebSocketProtobufRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be8cc7321fde08b2, []int{2}
}

func (m *WebSocketProtobufRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebSocketProtobufRequest.Unmarshal(m, b)
}
func (m *WebSocketProtobufRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebSocketProtobufRequest.Marshal(b, m, deterministic)
}
func (m *WebSocketProtobufRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebSocketProtobufRequest.Merge(m, src)
}
func (m *WebSocketProtobufRequest) XXX_Size() int {
	return xxx_messageInfo_WebSocketProtobufRequest.Size(m)
}
func (m *WebSocketProtobufRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WebSocketProtobufRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WebSocketProtobufRequest proto.InternalMessageInfo

func (m *WebSocketProtobufRequest) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *WebSocketProtobufRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *WebSocketProtobufRequest) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *WebSocketProtobufRequest) GetPayload() *anypb.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type WebSocketProtobufResponse struct {
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	HasMore   bool   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*WebSocketProtobufResponse_Ok
	//	*WebSocketProtobufResponse_Error
	Payload              isWebSocketProtobufResponse_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *WebSocketProtobufResponse) Reset()         { *m = WebSocketProtobufResponse{} }
func (m *WebSocketProtobufResponse) String() string { return proto.CompactTextString(m) }
func (*WebSocketProtobufResponse) ProtoMessage()    {}
func (*WebSocketProtobufResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be8cc7321fde08b2, []int{3}
}

func (m *WebSocketProtobufResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebSocketProtobufResponse.Unmarshal(m, b)
}
func (m *WebSocketProtobufResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebSocketProtobufResponse.Marshal(b, m, deterministic)
}
func (m *WebSocketProtobufResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebSocketProtobufResponse.Merge(m, src)
}
func (m *WebSocketProtobufResponse) XXX_Size() int {
	return xxx_messageInfo_WebSocketProtobufResponse.Size(m)
}
func (m *WebSocketProtobufResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WebSocketProtobufResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WebSocketProtobufResponse proto.InternalMessageInfo

func (m *WebSocketProtobufResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *WebSocketProtobufResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type isWebSocketProtobufResponse_Payload interface {
	isWebSocketProtobufResponse_Payload()
}

type WebSocketProtobufResponse_Ok struct {
	Ok *anypb.Any `protobuf:"bytes,3,opt,name=ok,proto3,oneof"`
}

type WebSocketProtobufResponse_Error struct {
	Error *WebSocketError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*WebSocketProtobufResponse_Ok) isWebSocketProtobufResponse_Payload() {}

func (*WebSocketProtobufResponse_Error) isWebSocketProtobufResponse_Payload() {}

func (m *WebSocketProtobufResponse) GetPayload() isWebSocketProtobufResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *WebSocketProtobufResponse) GetOk() *anypb.Any {
	if x, ok := m.GetPayload().(*WebSocketProtobufResponse_Ok); ok {
		return x.Ok
	}
	return nil
}

func (m *WebSocketProtobufResponse) GetError() *WebSocketError {
	if x, ok := m.GetPayload().(*WebSocketProtobufResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*WebSocketProtobufResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*WebSocketProtobufResponse_Ok)(nil),
		(*WebSocketProtobufResponse_Error)(nil),
	}
}

func init() {
	proto.RegisterType((*RestEmptyResponse)(nil), "restrpc.RestEmptyResponse")
	proto.RegisterType((*WebSocketError)(nil), "restrpc.WebSocketError")
	proto.RegisterType((*WebSocketProtobufRequest)(nil), "restrpc.WebSocketProtobufRequest")
	proto.RegisterType((*WebSocketProtobufResponse)(nil), "restrpc.WebSocketProtobufResponse")
}

func init() { proto.RegisterFile("restrpc/rest.proto", fileDescriptor_be8cc7321fde08b2) }

var fileDescriptor_be8cc7321fde08b2 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xdf, 0x6a, 0x9c, 0x40,
	0x14, 0xc6, 0x77, 0xec, 0x1f, 0x75, 0x4a, 0x0b, 0x9d, 0x16, 0xea, 0x6e, 0x69, 0x11, 0x2f, 0x8a,
	0x94, 0x56, 0x21, 0x79, 0x82, 0x6c, 0x58, 0xb2, 0xb9, 0x08, 0x84, 0xc9, 0x45, 0x20, 0x37, 0x32,
	0xea, 0x59, 0x5d, 0x5c, 0x3d, 0x93, 0x99, 0xf1, 0xc2, 0xb7, 0xc9, 0x6b, 0xe4, 0xed, 0x82, 0xab,
	0x2e, 0x6c, 0x48, 0x72, 0x21, 0xce, 0x39, 0xf3, 0x71, 0xce, 0xef, 0x3b, 0x67, 0x28, 0x53, 0xa0,
	0x8d, 0x92, 0x59, 0xdc, 0xff, 0x23, 0xa9, 0xd0, 0x20, 0xb3, 0xc7, 0xdc, 0xe2, 0xf7, 0x74, 0x29,
	0x9a, 0x4e, 0xa6, 0x71, 0x81, 0x58, 0xec, 0x20, 0x11, 0x4d, 0x37, 0x08, 0x83, 0x6f, 0xf4, 0x2b,
	0x07, 0x6d, 0x56, 0xb5, 0x34, 0x1d, 0x07, 0x2d, 0xb1, 0xd1, 0x10, 0x5c, 0xd0, 0x2f, 0xb7, 0x90,
	0xde, 0x60, 0x56, 0x81, 0x59, 0x29, 0x85, 0x8a, 0xfd, 0xa4, 0x6e, 0x69, 0x8c, 0x4c, 0x32, 0xcc,
	0xc1, 0x23, 0x3e, 0x09, 0x3f, 0x73, 0xa7, 0x4f, 0x9c, 0x63, 0x0e, 0xcc, 0xa3, 0x76, 0x0d, 0x5a,
	0x8b, 0x02, 0x3c, 0xcb, 0x27, 0xa1, 0xcb, 0xa7, 0x30, 0x78, 0x20, 0xd4, 0x3b, 0x54, 0xba, 0xee,
	0x1b, 0xa6, 0xed, 0x86, 0xc3, 0x7d, 0x0b, 0xda, 0xb0, 0x05, 0x75, 0xa0, 0xc9, 0x25, 0x6e, 0x1b,
	0xb3, 0x2f, 0xe9, 0xf2, 0x43, 0xcc, 0x7e, 0x51, 0xaa, 0x06, 0x59, 0xb2, 0xcd, 0xc7, 0xaa, 0xee,
	0x98, 0xb9, 0xcc, 0xd9, 0x9c, 0x3a, 0xa5, 0xd0, 0x49, 0x8d, 0x0a, 0xbc, 0x77, 0x3e, 0x09, 0x1d,
	0x6e, 0x97, 0x42, 0x5f, 0xa1, 0x02, 0x16, 0x51, 0x5b, 0x8a, 0x6e, 0x87, 0x22, 0xf7, 0xde, 0xfb,
	0x24, 0xfc, 0x74, 0xf2, 0x3d, 0x1a, 0x4c, 0x0f, 0x86, 0xd3, 0x76, 0x13, 0x9d, 0x35, 0x1d, 0x9f,
	0x44, 0xc1, 0x23, 0xa1, 0xf3, 0x17, 0x10, 0x87, 0x49, 0x3c, 0xe3, 0x20, 0x6f, 0x71, 0x58, 0xc7,
	0x1c, 0x7f, 0xa8, 0x85, 0xd5, 0x1e, 0xee, 0x15, 0x84, 0xf5, 0x8c, 0x5b, 0x58, 0xb1, 0x98, 0x7e,
	0x80, 0x7e, 0xc4, 0x23, 0xed, 0x8f, 0x68, 0x5c, 0x58, 0x74, 0xbc, 0x81, 0xf5, 0x8c, 0x0f, 0xba,
	0xa5, 0x7b, 0x30, 0xb8, 0xfc, 0x77, 0xf7, 0xb7, 0xd8, 0x9a, 0xb2, 0x4d, 0xa3, 0x0c, 0xeb, 0x58,
	0x56, 0xe6, 0x7f, 0x26, 0x74, 0xd9, 0x1f, 0xf2, 0x78, 0xd7, 0xf4, 0xdf, 0xf4, 0x2c, 0x94, 0xcc,
	0xd2, 0x8f, 0xfb, 0xee, 0xa7, 0x4f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xa3, 0x39, 0x60, 0x30,
	0x02, 0x00, 0x00,
}
