// Code generated by protoc-gen-go. DO NOT EDIT.
// source: restrpc/help/rest_help.proto

package help

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RestEndpoint struct {
	URI                  string   `protobuf:"bytes,1,opt,name=URI,proto3" json:"URI,omitempty"`
	ShortDescription     string   `protobuf:"bytes,2,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestEndpoint) Reset()         { *m = RestEndpoint{} }
func (m *RestEndpoint) String() string { return proto.CompactTextString(m) }
func (*RestEndpoint) ProtoMessage()    {}
func (*RestEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_9403c8f76ee6cdf6, []int{0}
}

func (m *RestEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestEndpoint.Unmarshal(m, b)
}
func (m *RestEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestEndpoint.Marshal(b, m, deterministic)
}
func (m *RestEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestEndpoint.Merge(m, src)
}
func (m *RestEndpoint) XXX_Size() int {
	return xxx_messageInfo_RestEndpoint.Size(m)
}
func (m *RestEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_RestEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_RestEndpoint proto.InternalMessageInfo

func (m *RestEndpoint) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func (m *RestEndpoint) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

type RestCommandCategory struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          []string               `protobuf:"bytes,2,rep,name=description,proto3" json:"description,omitempty"`
	Endpoints            []*RestEndpoint        `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Subcategory          []*RestCommandCategory `protobuf:"bytes,4,rep,name=subcategory,proto3" json:"subcategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RestCommandCategory) Reset()         { *m = RestCommandCategory{} }
func (m *RestCommandCategory) String() string { return proto.CompactTextString(m) }
func (*RestCommandCategory) ProtoMessage()    {}
func (*RestCommandCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_9403c8f76ee6cdf6, []int{1}
}

func (m *RestCommandCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestCommandCategory.Unmarshal(m, b)
}
func (m *RestCommandCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestCommandCategory.Marshal(b, m, deterministic)
}
func (m *RestCommandCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestCommandCategory.Merge(m, src)
}
func (m *RestCommandCategory) XXX_Size() int {
	return xxx_messageInfo_RestCommandCategory.Size(m)
}
func (m *RestCommandCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_RestCommandCategory.DiscardUnknown(m)
}

var xxx_messageInfo_RestCommandCategory proto.InternalMessageInfo

func (m *RestCommandCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RestCommandCategory) GetDescription() []string {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *RestCommandCategory) GetEndpoints() []*RestEndpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *RestCommandCategory) GetSubcategory() []*RestCommandCategory {
	if m != nil {
		return m.Subcategory
	}
	return nil
}

type RestMasterHelpResponse struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          []string               `protobuf:"bytes,2,rep,name=description,proto3" json:"description,omitempty"`
	Category             []*RestCommandCategory `protobuf:"bytes,3,rep,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RestMasterHelpResponse) Reset()         { *m = RestMasterHelpResponse{} }
func (m *RestMasterHelpResponse) String() string { return proto.CompactTextString(m) }
func (*RestMasterHelpResponse) ProtoMessage()    {}
func (*RestMasterHelpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9403c8f76ee6cdf6, []int{2}
}

func (m *RestMasterHelpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestMasterHelpResponse.Unmarshal(m, b)
}
func (m *RestMasterHelpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestMasterHelpResponse.Marshal(b, m, deterministic)
}
func (m *RestMasterHelpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestMasterHelpResponse.Merge(m, src)
}
func (m *RestMasterHelpResponse) XXX_Size() int {
	return xxx_messageInfo_RestMasterHelpResponse.Size(m)
}
func (m *RestMasterHelpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestMasterHelpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestMasterHelpResponse proto.InternalMessageInfo

func (m *RestMasterHelpResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RestMasterHelpResponse) GetDescription() []string {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *RestMasterHelpResponse) GetCategory() []*RestCommandCategory {
	if m != nil {
		return m.Category
	}
	return nil
}

type Field struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          []string `protobuf:"bytes,2,rep,name=description,proto3" json:"description,omitempty"`
	Repeated             bool     `protobuf:"varint,3,opt,name=repeated,proto3" json:"repeated,omitempty"`
	Type                 *Type    `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_9403c8f76ee6cdf6, []int{3}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetDescription() []string {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Field) GetRepeated() bool {
	if m != nil {
		return m.Repeated
	}
	return false
}

func (m *Field) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

type Type struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          []string `protobuf:"bytes,2,rep,name=description,proto3" json:"description,omitempty"`
	Fields               []*Field `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}
func (*Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_9403c8f76ee6cdf6, []int{4}
}

func (m *Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type.Unmarshal(m, b)
}
func (m *Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type.Marshal(b, m, deterministic)
}
func (m *Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type.Merge(m, src)
}
func (m *Type) XXX_Size() int {
	return xxx_messageInfo_Type.Size(m)
}
func (m *Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Type proto.InternalMessageInfo

func (m *Type) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Type) GetDescription() []string {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Type) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type RestHelpResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Description          []string `protobuf:"bytes,3,rep,name=description,proto3" json:"description,omitempty"`
	Request              *Type    `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	Response             *Type    `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestHelpResponse) Reset()         { *m = RestHelpResponse{} }
func (m *RestHelpResponse) String() string { return proto.CompactTextString(m) }
func (*RestHelpResponse) ProtoMessage()    {}
func (*RestHelpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9403c8f76ee6cdf6, []int{5}
}

func (m *RestHelpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestHelpResponse.Unmarshal(m, b)
}
func (m *RestHelpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestHelpResponse.Marshal(b, m, deterministic)
}
func (m *RestHelpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestHelpResponse.Merge(m, src)
}
func (m *RestHelpResponse) XXX_Size() int {
	return xxx_messageInfo_RestHelpResponse.Size(m)
}
func (m *RestHelpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestHelpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestHelpResponse proto.InternalMessageInfo

func (m *RestHelpResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RestHelpResponse) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *RestHelpResponse) GetDescription() []string {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *RestHelpResponse) GetRequest() *Type {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *RestHelpResponse) GetResponse() *Type {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*RestEndpoint)(nil), "help.RestEndpoint")
	proto.RegisterType((*RestCommandCategory)(nil), "help.RestCommandCategory")
	proto.RegisterType((*RestMasterHelpResponse)(nil), "help.RestMasterHelpResponse")
	proto.RegisterType((*Field)(nil), "help.Field")
	proto.RegisterType((*Type)(nil), "help.Type")
	proto.RegisterType((*RestHelpResponse)(nil), "help.RestHelpResponse")
}

func init() { proto.RegisterFile("restrpc/help/rest_help.proto", fileDescriptor_9403c8f76ee6cdf6) }

var fileDescriptor_9403c8f76ee6cdf6 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcd, 0xaa, 0xd3, 0x40,
	0x14, 0xc7, 0x89, 0x49, 0xbf, 0x4e, 0x5c, 0xd4, 0x11, 0x64, 0x14, 0x91, 0x10, 0x45, 0x02, 0x62,
	0xa3, 0x15, 0x57, 0xee, 0xac, 0x8a, 0x2e, 0xba, 0x19, 0x74, 0xe3, 0xa6, 0xa4, 0xc9, 0xb1, 0x09,
	0x26, 0x99, 0x71, 0x66, 0x2a, 0xe4, 0x01, 0xee, 0xfb, 0xdc, 0xf5, 0x7d, 0xba, 0xcb, 0x4c, 0xd3,
	0x34, 0xb7, 0xbd, 0x50, 0xe8, 0x22, 0x70, 0x3e, 0xfe, 0x73, 0xce, 0xef, 0x4c, 0xe6, 0xc0, 0x73,
	0x89, 0x4a, 0x4b, 0x91, 0xc6, 0x39, 0x96, 0x22, 0x36, 0xce, 0xca, 0x58, 0x33, 0x21, 0xb9, 0xe6,
	0xc4, 0x33, 0x76, 0xb8, 0x84, 0x87, 0x0c, 0x95, 0xfe, 0x5a, 0x67, 0x82, 0x17, 0xb5, 0x26, 0x53,
	0x70, 0x7f, 0xb1, 0x1f, 0xd4, 0x09, 0x9c, 0x68, 0xc2, 0x8c, 0x49, 0xde, 0xc0, 0x23, 0x95, 0x73,
	0xa9, 0x57, 0x19, 0xaa, 0x54, 0x16, 0x42, 0x17, 0xbc, 0xa6, 0x0f, 0x6c, 0x7e, 0x6a, 0x13, 0x5f,
	0x0e, 0xf1, 0xf0, 0xc6, 0x81, 0xc7, 0xa6, 0xde, 0x82, 0x57, 0x55, 0x52, 0x67, 0x8b, 0x44, 0xe3,
	0x86, 0xcb, 0x86, 0x10, 0xf0, 0xea, 0xa4, 0xc2, 0xb6, 0xae, 0xb5, 0x49, 0x00, 0xfe, 0xdd, 0x92,
	0x6e, 0x34, 0x61, 0xfd, 0x10, 0x79, 0x07, 0x13, 0x6c, 0xc1, 0x14, 0x75, 0x03, 0x37, 0xf2, 0xe7,
	0x64, 0x66, 0x47, 0xe8, 0x33, 0xb3, 0x83, 0x88, 0x7c, 0x02, 0x5f, 0x6d, 0xd7, 0x69, 0xdb, 0x96,
	0x7a, 0xf6, 0xcc, 0xd3, 0xc3, 0x99, 0x23, 0x2e, 0xd6, 0x57, 0x87, 0x57, 0x0e, 0x3c, 0x31, 0xa2,
	0x65, 0xa2, 0x34, 0xca, 0xef, 0x58, 0x0a, 0x86, 0x4a, 0xf0, 0x5a, 0xe1, 0x85, 0xfc, 0x1f, 0x61,
	0xdc, 0xa1, 0xb8, 0xe7, 0x50, 0x3a, 0x69, 0xd8, 0xc0, 0xe0, 0x5b, 0x81, 0x65, 0x76, 0x61, 0xd7,
	0x67, 0x30, 0x96, 0x28, 0x30, 0xd1, 0x98, 0x51, 0x37, 0x70, 0xa2, 0x31, 0xeb, 0x7c, 0xf2, 0x02,
	0x3c, 0xdd, 0x08, 0xa4, 0x5e, 0xe0, 0x44, 0xfe, 0x1c, 0x76, 0x34, 0x3f, 0x1b, 0x81, 0xcc, 0xc6,
	0xc3, 0x04, 0x3c, 0xe3, 0x5d, 0xd8, 0xf9, 0x25, 0x0c, 0xff, 0x18, 0xf0, 0xfd, 0xcf, 0xf2, 0x77,
	0xf5, 0xed, 0x30, 0xac, 0x4d, 0x85, 0xd7, 0x0e, 0x4c, 0xcd, 0xfc, 0x67, 0xef, 0x97, 0xc2, 0x48,
	0xa1, 0xfc, 0x5f, 0xa4, 0xd8, 0x3e, 0xb7, 0xbd, 0x7b, 0x4c, 0xe2, 0x9e, 0x92, 0xbc, 0x82, 0x91,
	0xc4, 0x7f, 0x5b, 0x54, 0xfa, 0x9e, 0x51, 0xf7, 0x29, 0xf2, 0xda, 0xdc, 0xd4, 0x8e, 0x80, 0x0e,
	0x4e, 0x64, 0x5d, 0xee, 0xf3, 0xfb, 0xdf, 0xf1, 0xa6, 0xd0, 0xf9, 0x76, 0x3d, 0x4b, 0x79, 0x15,
	0x8b, 0xbf, 0xfa, 0x6d, 0x9a, 0xa8, 0xdc, 0x18, 0x59, 0x5c, 0xd6, 0xe6, 0x33, 0x5b, 0xd6, 0xdf,
	0xb6, 0xf5, 0xd0, 0x2e, 0xd9, 0x87, 0xdb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0x99, 0x02, 0x8f,
	0x84, 0x03, 0x00, 0x00,
}
