// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metaservice.proto

package lnrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetInfo2Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfo2Request) Reset()         { *m = GetInfo2Request{} }
func (m *GetInfo2Request) String() string { return proto.CompactTextString(m) }
func (*GetInfo2Request) ProtoMessage()    {}
func (*GetInfo2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{0}
}

func (m *GetInfo2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfo2Request.Unmarshal(m, b)
}
func (m *GetInfo2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfo2Request.Marshal(b, m, deterministic)
}
func (m *GetInfo2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfo2Request.Merge(m, src)
}
func (m *GetInfo2Request) XXX_Size() int {
	return xxx_messageInfo_GetInfo2Request.Size(m)
}
func (m *GetInfo2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfo2Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfo2Request proto.InternalMessageInfo

type GetInfo2Response struct {
	Neutrino             *NeutrinoInfo    `protobuf:"bytes,1,opt,name=neutrino,proto3" json:"neutrino,omitempty"`
	Wallet               *WalletInfo      `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Lightning            *GetInfoResponse `protobuf:"bytes,3,opt,name=lightning,proto3" json:"lightning,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetInfo2Response) Reset()         { *m = GetInfo2Response{} }
func (m *GetInfo2Response) String() string { return proto.CompactTextString(m) }
func (*GetInfo2Response) ProtoMessage()    {}
func (*GetInfo2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{1}
}

func (m *GetInfo2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfo2Response.Unmarshal(m, b)
}
func (m *GetInfo2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfo2Response.Marshal(b, m, deterministic)
}
func (m *GetInfo2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfo2Response.Merge(m, src)
}
func (m *GetInfo2Response) XXX_Size() int {
	return xxx_messageInfo_GetInfo2Response.Size(m)
}
func (m *GetInfo2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfo2Response.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfo2Response proto.InternalMessageInfo

func (m *GetInfo2Response) GetNeutrino() *NeutrinoInfo {
	if m != nil {
		return m.Neutrino
	}
	return nil
}

func (m *GetInfo2Response) GetWallet() *WalletInfo {
	if m != nil {
		return m.Wallet
	}
	return nil
}

func (m *GetInfo2Response) GetLightning() *GetInfoResponse {
	if m != nil {
		return m.Lightning
	}
	return nil
}

type ChangePasswordRequest struct {
	//
	//current_password should be the current valid passphrase used to unlock the daemon.
	CurrentPassphrase string `protobuf:"bytes,1,opt,name=current_passphrase,json=currentPassphrase,proto3" json:"current_passphrase,omitempty"`
	//
	//Binary form of current_passphrase, if specified will override current_passphrase.
	//When using JSON, this field must be encoded as base64.
	CurrentPasswordBin []byte `protobuf:"bytes,2,opt,name=current_password_bin,json=currentPasswordBin,proto3" json:"current_password_bin,omitempty"`
	//
	//new_passphrase should be the new passphrase that will be needed to unlock the
	//daemon.
	NewPassphrase string `protobuf:"bytes,3,opt,name=new_passphrase,json=newPassphrase,proto3" json:"new_passphrase,omitempty"`
	//
	//Binary form of new_passphrase, if specified will override new_passphrase.
	//When using JSON, this field must be encoded as base64.
	NewPassphraseBin []byte `protobuf:"bytes,4,opt,name=new_passphrase_bin,json=newPassphraseBin,proto3" json:"new_passphrase_bin,omitempty"`
	//wallet_name is optional, if specified will override default wallet.db
	WalletName           string   `protobuf:"bytes,5,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{2}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetCurrentPassphrase() string {
	if m != nil {
		return m.CurrentPassphrase
	}
	return ""
}

func (m *ChangePasswordRequest) GetCurrentPasswordBin() []byte {
	if m != nil {
		return m.CurrentPasswordBin
	}
	return nil
}

func (m *ChangePasswordRequest) GetNewPassphrase() string {
	if m != nil {
		return m.NewPassphrase
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassphraseBin() []byte {
	if m != nil {
		return m.NewPassphraseBin
	}
	return nil
}

func (m *ChangePasswordRequest) GetWalletName() string {
	if m != nil {
		return m.WalletName
	}
	return ""
}

type ChangePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{3}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

type CheckPasswordRequest struct {
	//
	//current_password should be the current valid passphrase used to unlock the daemon.
	WalletPassphrase string `protobuf:"bytes,1,opt,name=wallet_passphrase,json=walletPassphrase,proto3" json:"wallet_passphrase,omitempty"`
	//
	//Binary form of current_passphrase, if specified will override current_passphrase.
	//When using JSON, this field must be encoded as base64.
	WalletPasswordBin []byte `protobuf:"bytes,2,opt,name=wallet_password_bin,json=walletPasswordBin,proto3" json:"wallet_password_bin,omitempty"`
	//wallet_name is optional, if specified will override default wallet.db
	WalletName           string   `protobuf:"bytes,3,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPasswordRequest) Reset()         { *m = CheckPasswordRequest{} }
func (m *CheckPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*CheckPasswordRequest) ProtoMessage()    {}
func (*CheckPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{4}
}

func (m *CheckPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPasswordRequest.Unmarshal(m, b)
}
func (m *CheckPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPasswordRequest.Marshal(b, m, deterministic)
}
func (m *CheckPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPasswordRequest.Merge(m, src)
}
func (m *CheckPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_CheckPasswordRequest.Size(m)
}
func (m *CheckPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPasswordRequest proto.InternalMessageInfo

func (m *CheckPasswordRequest) GetWalletPassphrase() string {
	if m != nil {
		return m.WalletPassphrase
	}
	return ""
}

func (m *CheckPasswordRequest) GetWalletPasswordBin() []byte {
	if m != nil {
		return m.WalletPasswordBin
	}
	return nil
}

func (m *CheckPasswordRequest) GetWalletName() string {
	if m != nil {
		return m.WalletName
	}
	return ""
}

type CheckPasswordResponse struct {
	ValidPassphrase      bool     `protobuf:"varint,1,opt,name=valid_passphrase,json=validPassphrase,proto3" json:"valid_passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPasswordResponse) Reset()         { *m = CheckPasswordResponse{} }
func (m *CheckPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*CheckPasswordResponse) ProtoMessage()    {}
func (*CheckPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{5}
}

func (m *CheckPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPasswordResponse.Unmarshal(m, b)
}
func (m *CheckPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPasswordResponse.Marshal(b, m, deterministic)
}
func (m *CheckPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPasswordResponse.Merge(m, src)
}
func (m *CheckPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_CheckPasswordResponse.Size(m)
}
func (m *CheckPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPasswordResponse proto.InternalMessageInfo

func (m *CheckPasswordResponse) GetValidPassphrase() bool {
	if m != nil {
		return m.ValidPassphrase
	}
	return false
}

type CrashRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrashRequest) Reset()         { *m = CrashRequest{} }
func (m *CrashRequest) String() string { return proto.CompactTextString(m) }
func (*CrashRequest) ProtoMessage()    {}
func (*CrashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{6}
}

func (m *CrashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrashRequest.Unmarshal(m, b)
}
func (m *CrashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrashRequest.Marshal(b, m, deterministic)
}
func (m *CrashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrashRequest.Merge(m, src)
}
func (m *CrashRequest) XXX_Size() int {
	return xxx_messageInfo_CrashRequest.Size(m)
}
func (m *CrashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrashRequest proto.InternalMessageInfo

type CrashResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrashResponse) Reset()         { *m = CrashResponse{} }
func (m *CrashResponse) String() string { return proto.CompactTextString(m) }
func (*CrashResponse) ProtoMessage()    {}
func (*CrashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{7}
}

func (m *CrashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrashResponse.Unmarshal(m, b)
}
func (m *CrashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrashResponse.Marshal(b, m, deterministic)
}
func (m *CrashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrashResponse.Merge(m, src)
}
func (m *CrashResponse) XXX_Size() int {
	return xxx_messageInfo_CrashResponse.Size(m)
}
func (m *CrashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrashResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetInfo2Request)(nil), "lnrpc.GetInfo2Request")
	proto.RegisterType((*GetInfo2Response)(nil), "lnrpc.GetInfo2Response")
	proto.RegisterType((*ChangePasswordRequest)(nil), "lnrpc.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "lnrpc.ChangePasswordResponse")
	proto.RegisterType((*CheckPasswordRequest)(nil), "lnrpc.CheckPasswordRequest")
	proto.RegisterType((*CheckPasswordResponse)(nil), "lnrpc.CheckPasswordResponse")
	proto.RegisterType((*CrashRequest)(nil), "lnrpc.CrashRequest")
	proto.RegisterType((*CrashResponse)(nil), "lnrpc.CrashResponse")
}

func init() { proto.RegisterFile("metaservice.proto", fileDescriptor_b3fb5294949b9545) }

var fileDescriptor_b3fb5294949b9545 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0x5f, 0x8b, 0xd3, 0x40,
	0x14, 0xc5, 0xe9, 0xd6, 0x5d, 0xda, 0xdb, 0xed, 0x9f, 0xcc, 0xd6, 0x35, 0xc4, 0x15, 0x25, 0x28,
	0xb8, 0xe8, 0xa6, 0x52, 0x05, 0x1f, 0x7c, 0x6b, 0x41, 0x51, 0xd8, 0x65, 0x89, 0x0f, 0x82, 0x2f,
	0x65, 0x9a, 0x5e, 0x9b, 0xd0, 0x74, 0x32, 0xce, 0x4c, 0xb7, 0x5f, 0xc4, 0x67, 0x9f, 0xfc, 0x7c,
	0x7e, 0x06, 0xc9, 0xcc, 0xa4, 0x4d, 0xd2, 0xf5, 0xa1, 0x90, 0x9e, 0xfb, 0xcb, 0xe1, 0xcc, 0x99,
	0xdb, 0x82, 0xb3, 0x46, 0x45, 0x25, 0x8a, 0xbb, 0x24, 0xc2, 0x80, 0x8b, 0x4c, 0x65, 0xe4, 0x38,
	0x65, 0x82, 0x47, 0x5e, 0x9b, 0xaf, 0x94, 0x51, 0xbc, 0xb6, 0xe0, 0x91, 0x79, 0xf4, 0x1d, 0xe8,
	0x7f, 0x42, 0xf5, 0x99, 0xfd, 0xc8, 0xc6, 0x21, 0xfe, 0xdc, 0xa0, 0x54, 0xfe, 0x9f, 0x06, 0x0c,
	0xf6, 0x9a, 0xe4, 0x19, 0x93, 0x48, 0x46, 0xd0, 0x62, 0xb8, 0x51, 0x22, 0x61, 0x99, 0xdb, 0x78,
	0xd6, 0x78, 0xd9, 0x19, 0x9f, 0x05, 0xda, 0x37, 0xb8, 0xb1, 0x72, 0xce, 0x87, 0x3b, 0x88, 0x5c,
	0xc2, 0xc9, 0x96, 0xa6, 0x29, 0x2a, 0xf7, 0x48, 0xe3, 0x8e, 0xc5, 0xbf, 0x69, 0x51, 0xc3, 0x16,
	0x20, 0xef, 0xa0, 0x9d, 0x26, 0xcb, 0x58, 0xb1, 0x84, 0x2d, 0xdd, 0xa6, 0xa6, 0xcf, 0x2d, 0x6d,
	0x73, 0x14, 0x31, 0xc2, 0x3d, 0xe8, 0xff, 0x6d, 0xc0, 0xc3, 0x69, 0x4c, 0xd9, 0x12, 0x6f, 0xa9,
	0x94, 0xdb, 0x4c, 0x2c, 0xec, 0x01, 0xc8, 0x15, 0x90, 0x68, 0x23, 0x04, 0x32, 0x35, 0xe3, 0x54,
	0x4a, 0x1e, 0x0b, 0x2a, 0x51, 0xa7, 0x6e, 0x87, 0x8e, 0x9d, 0xdc, 0xee, 0x06, 0xe4, 0x0d, 0x0c,
	0xcb, 0x78, 0xee, 0x34, 0x9b, 0x27, 0x4c, 0xe7, 0x3e, 0x0d, 0x49, 0xe9, 0x85, 0x7c, 0x34, 0x49,
	0x18, 0x79, 0x01, 0x3d, 0x86, 0xdb, 0xb2, 0x79, 0x53, 0x9b, 0x77, 0x19, 0x6e, 0x4b, 0xc6, 0xaf,
	0x81, 0x54, 0x31, 0x6d, 0xfb, 0x40, 0xdb, 0x0e, 0x2a, 0x68, 0x6e, 0xfa, 0x14, 0x3a, 0xa6, 0x8f,
	0x19, 0xa3, 0x6b, 0x74, 0x8f, 0xb5, 0x23, 0x18, 0xe9, 0x86, 0xae, 0xd1, 0x77, 0xe1, 0xbc, 0x7e,
	0x5e, 0xd3, 0x8a, 0xff, 0xab, 0x01, 0xc3, 0x69, 0x8c, 0xd1, 0xaa, 0xde, 0xc4, 0x2b, 0x70, 0xac,
	0xe7, 0x41, 0x11, 0x03, 0x33, 0x28, 0xc5, 0x0d, 0xe0, 0xac, 0x04, 0xd7, 0x6a, 0x70, 0xf6, 0x78,
	0xd1, 0x42, 0x2d, 0x70, 0xf3, 0x20, 0xf0, 0x24, 0xbf, 0xa0, 0x4a, 0x2a, 0xbb, 0x4c, 0x97, 0x30,
	0xb8, 0xa3, 0x69, 0xb2, 0xa8, 0xa7, 0x6a, 0x85, 0x7d, 0xad, 0xef, 0x43, 0xf9, 0x3d, 0x38, 0x9d,
	0x0a, 0x2a, 0xe3, 0x62, 0x39, 0xfb, 0xd0, 0xb5, 0xdf, 0x8d, 0xd7, 0xf8, 0xf7, 0x11, 0x74, 0xae,
	0x51, 0xd1, 0xaf, 0x66, 0xe7, 0xc9, 0x07, 0x68, 0x15, 0xcb, 0x4b, 0x6a, 0x5b, 0x54, 0x6c, 0xb8,
	0xf7, 0xe8, 0x40, 0xb7, 0xc1, 0xae, 0xa1, 0x57, 0xad, 0x98, 0x5c, 0x58, 0xf4, 0xde, 0x4d, 0xf3,
	0x9e, 0xfc, 0x67, 0x6a, 0xed, 0xbe, 0x40, 0xb7, 0x52, 0x00, 0x79, 0xbc, 0xe3, 0x0f, 0x2f, 0xcb,
	0xbb, 0xb8, 0x7f, 0x68, 0xbd, 0xde, 0x03, 0x7c, 0xcc, 0x44, 0x84, 0xfa, 0xf4, 0xa4, 0xf8, 0xf1,
	0x95, 0xbb, 0xf1, 0x86, 0x55, 0xd1, 0xbc, 0x38, 0x79, 0xfe, 0xdd, 0x5f, 0x26, 0x2a, 0xde, 0xcc,
	0x83, 0x28, 0x5b, 0x8f, 0xf8, 0x4a, 0x5d, 0x45, 0x54, 0xc6, 0xf9, 0xc3, 0x62, 0x94, 0xb2, 0xfc,
	0x23, 0x78, 0x34, 0x3f, 0xd1, 0x7f, 0x07, 0x6f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xd9,
	0x47, 0xd9, 0x40, 0x04, 0x00, 0x00,
}
